```{r}
library(readxl)
train= read_excel("Absenteeism_at_work_Project.xls") 
train <- data.frame(train)
summary(train)
#install.packages('Hmisc')
library(Hmisc)
```
```{r}
#summary(train)
#boxplot(train)
#da <- train
#install.packages(c("forcats", "DataExplorer", "ggthemes","grid","gridExtra","factoextra","FactoMineR"))
library(forcats)
library(dplyr)
library(ggplot2)
library(plyr)
library(DataExplorer)
library(ggthemes)
install.packages("psych")
library(psych) 
pairs.panels(train) 
library(grid) 
library(gridExtra) 
library(factoextra) 
library(FactoMineR) 
da=train
library(dplyr)
```


```{r}
#missing value imputation
for (i in (1:21)){
  train[i]=impute(train[i],median)
}
```

```{r}
#converting every column to numeric
col <- c(1:21)
train[col]=as.numeric(unlist(train[col]))
#Converting categorical data to factor type
for (i in c(1,2,3,4,5,12,13,15,16)) {
  train[,i]=as.factor(unlist(train[i]))
}
```

```{r}
summary(train)
boxplot(train)
```
```{r}

#da <- train
#install.packages(c("forcats", "DataExplorer", "ggthemes","grid","gridExtra","factoextra","FactoMineR"))
#library(forcats)
#library(dplyr)
#library(ggplot2)
#library(plyr)
#library(DataExplorer)
#library(ggthemes)
#install.packages("psych")
library(psych) 
#pairs.panels(train) 
library(grid) 
library(gridExtra) 
#install.packages("factoextra", lib="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
library(factoextra) 
library(FactoMineR) 
da=train
library(dplyr)
```

```{r}
#recoding categorical data
da$Reason.for.absence=factor(da$Reason.for.absence,levels =
c(0:19,21:28),labels = c('infectious,parasitic diseases','Neoplasms','Diseases of the blood','Endocrine and metabolic diseases',
                         'Mental and behavioural disorders', 'Diseases of the nervous system','Diseases of the eye and adnexa',
                          'Diseases of the earand mastoid process','Diseases of the circulatory system','Diseases of the respiratory system',
                          'Diseases of the digestive system','Diseases of the skin and subcutaneous tissue',
                          'Diseases of the musculoskeletal system and connective tissue','Diseases of the genitourinary system',
                         'Pregnancy, childbirth and the puerperium', 'Certain conditions originating in the perinatal','Congenital malformations,deformations                           and chromosomal abnormalities','Symptoms, signs and abnormal clinical  findings',
                             'Injury, poisoning and certain other consequences of external causes','causes of morbidity and mortality',
                             'Factors influencing health status and contact with health services','patient follow-up','medical consultation','blood                                       donation','laboratory examination','unjustified absence','physiotherapy',
                         'dental consultation'))
da$Month.of.absence=factor(da$Month.of.absence,levels=c(0:12),labels=c('None','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'))
da$Seasons <-factor(da$Seasons,levels=c(1:4),labels=c('summer','autumn','winter','spring'))
da$Education <-factor(da$Education,levels=c(1:4),labels=c('highschool','graduate','postgraduate','master& doctrate'))
da$Disciplinary.failure <- factor(da$Disciplinary.failure,levels=c(0:1),labels=c('No','Yes'))
da$Social.drinker <- factor(da$Social.drinker,levels=c(0:1),labels=c('No','Yes'))
da$Social.smoker <- factor(da$Social.smoker,levels=c(0:1),labels=c('No','Yes'))
da$Day.of.the.week<-factor(da$Day.of.the.week,levels=c(2:6),labels=c("Monday","Tuesday","Wednesday","Thursday","Friday"))
```

```{r}
# Data exploration-
p <- ggplot(da, aes(x = Education, fill = Education)) +geom_bar()
s <- ggplot(da, aes(x = Reason.for.absence, fill = Reason.for.absence)) + geom_bar()
SS <- ggplot(da, aes(x =  Social.smoker, fill =  Social.smoker))+ geom_bar()
SD <- ggplot(da, aes(x =  Social.drinker, fill =Social.drinker)) + geom_bar()
D <- ggplot(da, aes(x =  Disciplinary.failure, fill =Disciplinary.failure)) + geom_bar()
month<- ggplot(da, aes(x =  Month.of.absence, fill =Month.of.absence)) + geom_bar()
Day <- ggplot(da, aes(x = Day.of.the.week, fill =Day.of.the.week))+ geom_bar()
S <- ggplot(da, aes(x = Seasons,fill = Seasons)) + geom_bar()
plot(p)
plot(SS)
plot(S)
plot(SD)
plot(D)
plot(Day)
plot(month)
plot(s)
```

```{r}
#detach("package:dplyr", unload=TRUE)
```

```{r}
#selecting samples which have absenteeism time hours > 0
library(dplyr)
absent <- as.data.frame( da %>% select(everything()) %>%
filter(Absenteeism.time.in.hours > 0))
```

```{r}
#percentage absenteeism hours(>0) vs  seasons
season1 <- as.data.frame(absent %>% group_by(Seasons) %>%
                            summarise(count= n(), percent =round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(season1,aes(x= reorder(Seasons,percent), y= percent, fill = Seasons)) + geom_bar(stat='identity') + coord_flip() +
  geom_text(aes(label = percent), vjust = 1.1, hjust = 1.2) +
  xlab('Seasons')
```

```{r}
#percentage absenteeism hours(>0) vs  seasons
season1 <- as.data.frame(absent %>% group_by(Seasons) %>%
summarise(count= n(), percent =
round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(season1,aes(x= reorder(Seasons,percent), y= percent, fill= Seasons)) + geom_bar(stat='identity') + coord_flip() +
  geom_text(aes(label = percent), vjust = 1.1, hjust = 1.2) +
xlab('Seasons')

#percentage absenteeism hours vs  disciplinary failure
disciplinary <-as.data.frame(absent %>%
group_by(Disciplinary.failure) %>% summarise(count= n(), percent = round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(disciplinary,aes(x=reorder(Disciplinary.failure,percent), y= percent, fill =Disciplinary.failure)) + geom_bar(stat='identity') +
  coord_flip() +
  geom_text(aes(label = percent), vjust = 1.1, hjust = 1.2) +
  xlab('Disciplinary failure')

#percentage absenteeism hours vs Reason for absence
Reason <-  as.data.frame(absent %>% group_by(Reason.for.absence)
%>% summarise(count= n(), percent =round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(Reason,aes(x = reorder(Reason.for.absence,percent), y=percent, fill= Reason.for.absence)) + geom_bar(stat ='identity') + coord_flip() +         theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('Reason for absence')
##percentage absenteeism hours vs  day of the week
dayofweek <-  as.data.frame(absent %>% group_by(Day.of.the.week)
%>% summarise(count= n(), percent =round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(dayofweek,aes(x = reorder(Day.of.the.week,percent), y=percent, fill= Day.of.the.week)) + geom_bar(stat = 'identity') +
  coord_flip() + theme(legend.position='none') +geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) + xlab('Day.of.the.week')
##percentage absenteeism hours vs social smoker
socialsmoker <- as.data.frame(absent %>% group_by(Social.smoker) %>% summarise(count= n(), percent = round(count*100/nrow(absent),1))%>% arrange(desc(count))) 
ggplot(socialsmoker,aes(x = Social.smoker, y= percent, fill= Social.smoker)) + geom_bar(stat = 'identity') + coord_flip() + theme(legend.position='none') +geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) + xlab('Social.smoker')
##percentage absenteeism hours vs social drinker 
socialdrinker <-  as.data.frame(absent %>%
group_by(Social.drinker) %>% summarise(count= n(), percent =round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(socialdrinker,aes(x = Social.drinker, y= percent, fill=Social.drinker)) + geom_bar(stat = 'identity') + coord_flip() +
  theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('Social.drinker')
#percentage of absent people vs education
education=as.data.frame(absent %>% group_by(Education) %>%
summarise(count= n(), percent =
round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(education,aes(x = Education, y= percent, fill=Education)) + geom_bar(stat = 'identity') + coord_flip() +
  theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('Education')
#percentage of absent people vs people having pet
pet=as.data.frame(absent %>% group_by(Pet) %>% summarise(count=n(), percent = round(count*100/nrow(absent),1))%>%
arrange(desc(count)))
ggplot(pet,aes(x = Pet, y= percent, fill= Pet)) + geom_bar(stat= 'identity') + coord_flip() + theme(legend.position='none')   +
geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) + xlab('pet')
#percentage of absent people vs age
age=as.data.frame(absent %>% group_by(Age) %>% summarise(count= n(), percent = round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(age,aes(x = Age, y= percent, fill= Age)) + geom_bar(stat= 'identity') + coord_flip() + theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('age')
#percentage of absent people vs weight
weight=as.data.frame(absent %>% group_by(Weight) %>%
summarise(count= n(), percent =
round(count*100/nrow(absent),1))%>% arrange(desc(count)))
ggplot(weight,aes(x = Weight, y= percent, fill= Weight)) +
  geom_bar(stat = 'identity') + coord_flip() +
  theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('weight')
#percentage of absent people vs dist
dist=as.data.frame(absent %>%
group_by(Distance.from.Residence.to.Work) %>% summarise(count=n(), percent = round(count*100/nrow(absent),1))%>%
arrange(desc(count)))
ggplot(dist,aes(x = Distance.from.Residence.to.Work, y= percent,fill= Distance.from.Residence.to.Work)) + geom_bar(stat ='identity') + coord_flip() +   theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('dist from residance')
#percentage of absent people vs workload
workload=as.data.frame(absent %>%
group_by(Work.load.Average.day) %>% summarise(count= n(),percent = round(count*100/nrow(absent),1))%>%
arrange(desc(count)))
ggplot(workload,aes(x =Work.load.Average.day, y= percent, fill=Work.load.Average.day)) + geom_bar(stat = 'identity') +
  coord_flip() + theme(legend.position='none') +
  geom_text(aes(label = percent), vjust = 0.5, hjust = 1.1) +
  xlab('work load avg')
```
    
```{r}
#histogram of numerical features
hist(train$Transportation.expense)
hist(train$Distance.from.Residence.to.Work)
hist(train$Service.time)
hist(train$Age)
hist(train$Work.load.Average.day)
hist(train$Hit.target)
hist(train$Pet)
hist(train$Weight)
hist(train$Height)
hist(train$Son)
hist(train$Body.mass.index) 
hist(train$Absenteeism.time.in.hours) #boxplots of numerical features 
boxplot(train$Transportation.expense) 
boxplot(train$Distance.from.Residence.to.Work) 
boxplot(train$Service.time)
boxplot(train$Age)
boxplot(train$Work.load.Average.day)
boxplot( train$Hit.target)
boxplot(train$Weight)
boxplot(train$Body.mass.index)
boxplot(train$Absenteeism.time.in.hours)
library(RcmdrMisc)

```

```{r}
#anova by month of abscence
AnovaModel.1 <- (lm(Absenteeism.time.in.hours ~ Seasons, data =train))
Anova(AnovaModel.1)
# Absence Rate By Pet
install.packages('RcmdrMisc')
library(RcmdrMisc)
AnovaModel.2 <- (lm(da$Absenteeism.time.in.hours ~
Reason.for.absence, data = da))
Anova(AnovaModel.2)
# By Season
AnovaModel.3 <- (lm(da$Absenteeism.time.in.hours ~
Month.of.absence, data = da))
Anova(AnovaModel.3)# By Social smoker
AnovaModel.4 <- (lm(da$Absenteeism.time.in.hours ~
Social.smoker, data = da))
Anova(AnovaModel.4)
# By Social drinker
AnovaModel.5 <- (lm(da$Absenteeism.time.in.hours ~
Social.drinker, data = da))
Anova(AnovaModel.5)
# By Education
AnovaModel.7 <- (lm(da$Absenteeism.time.in.hours ~ Education,
data = da))
Anova(AnovaModel.7)
# By Disciplanary failure
AnovaModel.8 <- (lm(da$Absenteeism.time.in.hours ~
Disciplinary.failure, data = da))
Anova(AnovaModel.8)
```

```{r}
#Min max scaling of numerical data(as they have different ranges)
#note: not scaling target variable
for (i in c(1:13,15:16,18:20)){
  if (class(train[,i])=="numeric"){
    for (j in c(1:740)){
        train[j,i]=(train[j,i]-min(train[i]))/(max(train[i])-min(train[i]))
} }
}
```

```{r}
#replacing outliers
#replacing values greater than 0.95 quantile with values present in 0.95 quantile
#replacing values less than 0.05 quantile with values present in 0.05 quantile
qn = quantile(train$Absenteeism.time.in.hours, c(0.05, 0.95),na.rm = TRUE)
print(qn)
train$Absenteeism.time.in.hours[train$Absenteeism.time.in.hours<
qn[1]]=qn[1]
train$Absenteeism.time.in.hours[train$Absenteeism.time.in.hours>
qn[2]]=qn[2]

```
```{r}

#one hot encoding of categorical variables
#install.packages("dummies", lib="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
library(dummies)
hi=data.frame(dummy(train$Reason.for.absence))
train$Reason.for.absence=NULL
hi1=data.frame(dummy(train$Month.of.absence))
train$Month.of.absence=NULL
hi2=data.frame(dummy(train$Day.of.the.week))
train$Day.of.the.week=NULL
hi3=data.frame(dummy(train$Education))
train$Education=NULL
hi4=data.frame(dummy(train$Social.smoker))
train$Social.smoker=NULL
hi5=data.frame(dummy(train$Social.drinker))
train$Social.drinker=NULL
hi6=data.frame(dummy(train$Disciplinary.failure))
train$Disciplinary.failure=NULL
hi7=data.frame(dummy(train$Seasons))
train$Seasons=NULL
#combining binary features with original data
train=cbind(train,hi,hi1,hi2,hi3,hi4)
train=cbind(train,hi5,hi6,hi7)
```
```{r}
#correlation plot
library(caret)
# install.packages("corrplot", lib="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
library(corrplot)
target=train["Absenteeism.time.in.hours"]
corm=train[-1]#coorelation matrix
matrix=cor(corm)
#correlation plot
corrplot(matrix, method="pie")
```

```{r}
#removing features with value greater than 0.95
hc = findCorrelation(matrix, cutoff=0.95) # we can putt any value as a "cutoff"
#sorting out the columns to be removes
hc = sort(hc)
```

```{r}
#removing highly correlated columns
reduced_Data = corm[,-c(hc)]
```

```{r}
#combining the clean data with the factor variables of original data
new_train=cbind(train['ID'],reduced_Data) 
test=new_train[550:740,-1]
```

```{r}
install.packages('DAAG')
library(DAAG)
#feature selection using boruta package
install.packages("Boruta", lib="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
library(Boruta) 
new_train$Absenteeism.time.in.hours=log(new_train$Absenteeism.time.in.hours)
finail.boruta=Boruta(Absenteeism.time.in.hours~., data = new_train[,-1], doTrace = 2) 
print(finail.boruta)
selected_features=getSelectedAttributes(finail.boruta, withTentative = F)
set.seed(123)
#creating formula from boruta selected features 
formula=as.formula(paste("Absenteeism.time.in.hours~",paste(selected_features,collapse = "+")))
```

```{r}
#predictive models
# linear model
train_control <- trainControl(method = "repeatedcv",number = 10)
options(warn=-1)
lm_model<- train(formula,data=new_train[1:500,-1],metric="RMSE", method="lm",trControl=train_control)
pred=predict(lm_model,test)
# estimate variable importance
lm_importance <- varImp(lm_model, scale=FALSE)
# summarize importance
print(lm_model)
# plot importance
plot(lm_importance)
```View

